### Tensor
- sclar: 크기만 가짐. 0차원 텐서
- vector: 크기와 방향을 가짐. (N,)
- matrix: 행렬. grayscale 이미지, 좌표 시스템 등. (N,M)
- array: 3차원 이상의 배열. RGB 이미지, 행렬의 묶음, batch 등. (C,H,W)
- 딥러닝 모델에 데이터를 batch 단위로 입력할 때에 이미지 묶음을 표현하기 위해 일반적으로 4차원 array를 사용함. 이때 N이 batch size. (N,C,H,W)

### 예제 3.01 텐서 생성
torch.Tensor() 사용 추천
- torch.tensor(): 입력 데이터를 복사해서 텐서로 변환. 따라서 값이 무조건 있어야 함, 입력 데이터에 맞는 자료형으로 변환됨.
- torch.Tensor(): 기본형 텐서 생성. 값이 없으면 빈 텐서를 만들고, Float 자료형으로 변환됨.


In [1]:
# 예제 3.01 텐서 생성
import torch

print(torch.tensor([1, 2, 3])) # 소문자 사용. 자료형이 Int.
print(torch.Tensor([[1, 2, 3], [4, 5, 6]])) # 대문자 사용. 자료형이 Float으로 변환됨.
print(torch.LongTensor([1, 2, 3])) # 자료형을 선언하며 텐서를 생성 가능

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])


### 예제 3.02 텐서 속성
- .shape: 배열 형태
- .dtype: 자료형
- .device: 장치. 텐서의 GPU 가속 여부 확인

### 예제 3.03 텐서 차원 변환
- torch.reshape

In [2]:
# 예제 3.02 텐서 속성
tensor = torch.rand(1, 2)
print(tensor.shape) # 배열 형태
print(tensor.dtype) # 자료형
print(tensor.device) # 장치

# 예제 3.03 텐서 차원 변환
tensor = torch.rand(1, 2)
print(tensor)
print(tensor.shape) # 기존 shape (1,2)

tensor = tensor.reshape(2, 1)
print(tensor)
print(tensor.shape)

# 예제 3.04 텐서 자료형 설정
tensor = torch.rand((3, 3), dtype=torch.float) # 자료형 설정 가능
print(tensor)

torch.Size([1, 2])
torch.float32
cpu
tensor([[0.5224, 0.1717]])
torch.Size([1, 2])
tensor([[0.5224],
        [0.1717]])
torch.Size([2, 1])
tensor([[0.7204, 0.1475, 0.1046],
        [0.3497, 0.0752, 0.0536],
        [0.6605, 0.8767, 0.1519]])


### 예제 3.05 텐서 GPU 장치 설정
아래처럼 장치 variable 설정해서 CUDA 사용 여부에 따라 장치 설정 가능
- device = "cuda" if torch.cuda.is_available() else "cpu"
- tensor = torch.rand((1, 1), device=device)

### 예제 3.06 텐서 장치 변환
- 텐서이름.cuda(): cpu 텐서 gpu로
- 텐서이름.cpu(): gpu 텐서 cpu로

In [3]:
# 예제 3.05 텐서 GPU 장치 설정
device = "cuda" if torch.cuda.is_available() else "cpu"
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)
print(device)
print(cpu)
print(gpu)
print(tensor)

# 예제 3.06 텐서 장치 변환
cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()
cpu2gpu = cpu.to("cuda")
print(cpu)
print(gpu)
print(gpu2cpu)
print(cpu2gpu)

<ipython-input-3-0d814987b216>:4: UserWarning: The torch.cuda.*DtypeTensor constructors are no longer recommended. It's best to use methods such as torch.tensor(data, dtype=*, device='cuda') to create tensors. (Triggered internally at ../torch/csrc/tensor/python_tensor.cpp:83.)
  gpu = torch.cuda.FloatTensor([1, 2, 3])


cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.2767]], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')


### 예제 3.07 넘파이 배열의 텐서 변환
- torch.tensor(), torch.Tenser(), torch.from_numpy(배열이름)

### 예제 3.08 텐서의 넘파이 배열 변환
- a.detach().cpu().numpy()
- (1) .detach(): 텐서는 backpropagation을 위해 모든 연산을 기록하고 있기에 graph에서 분리된 텐서를 받기 위해 사용
- (2) .cpu(): cpu 텐서로 변환
- (3) .numpy(): numpy 배열로 변환

In [5]:
# 예제 3.07 넘파이 배열의 텐서 변환
import torch
import numpy as np

ndarray = np.array([1, 2, 3], dtype=np.uint8)
print(torch.tensor(ndarray))
print(torch.Tensor(ndarray))
print(torch.from_numpy(ndarray))

tensor = torch.cuda.FloatTensor([1, 2, 3])
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))
import torch

# 예제 3.08 텐서의 넘파이 배열 변환
tensor = torch.FloatTensor([1, 2, 3]).to("cuda")
ndarray = tensor.detach().cpu().numpy()
print(ndarray)
print(type(ndarray))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)
[1. 2. 3.]
<class 'numpy.ndarray'>
[1. 2. 3.]
<class 'numpy.ndarray'>
