### 손실 함수
- ground truth와 prediction 간의 오차를 계산하는 함수
- 신경망은 오차를 최소화하는 방법으로 학습을 진행함

### Optimization
- Objective function의 값을 최적화하는 weight, bias를 찾는 알고리즘
- Gradient descent: 손실 함수의 기울기 값이 작은 곳으로 이동해서 최적의 variable을 찾음
- Momentum, Adaptive gradient, Adam 등 다양한 알고리즘이 존재함

In [1]:
# 예제 3.11~3.17 단순 선형 회귀(넘파이)

import numpy as np

# 데이터 선언
x = np.array(
    [[1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]]
)
y = np.array(
    [[0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]]
)

# variable, lr 선언
weight = 0.0
bias = 0.0
learning_rate = 0.005

# epoch  설정
for epoch in range(10000):
    # 가설 설정
    y_hat = weight * x + bias

    # 손실 함수 선언
    cost = ((y - y_hat) ** 2).mean()

    # weight, bias 갱신
    weight = weight - learning_rate * ((y_hat - y) * x).mean() # w1 = w0-lr*(손실함수를 w로 편미분한 값)
    bias = bias - learning_rate * (y_hat - y).mean() # b1 = b0-lr*(손실함수를 b로 편미분한 값)

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight:.3f}, Bias : {bias:.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.872, Bias : -0.290, Cost : 1.377
Epoch : 2000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 3000, Weight : 0.878, Bias : -0.422, Cost : 1.372
Epoch : 4000, Weight : 0.879, Bias : -0.432, Cost : 1.372
Epoch : 5000, Weight : 0.879, Bias : -0.435, Cost : 1.372
Epoch : 6000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 7000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 8000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.436, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.436, Cost : 1.372


In [2]:
# 예제 3.18~3.24 단순 선형 회귀(파이토치)


import torch
from torch import optim

# 데이터 선언
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

# variable, lr, optimizer 초기화
weight = torch.zeros(1, requires_grad=True)
bias = torch.zeros(1, requires_grad=True)
learning_rate = 0.001
optimizer = optim.SGD([weight, bias], lr=learning_rate)

# epoch  설정
for epoch in range(10000):
    hypothesis = weight * x + bias # 가설 설정
    cost = torch.mean((hypothesis - y) ** 2) # 손실 함수 선언

    optimizer.zero_grad() # gradient 0으로 초기화
    cost.backward() # 역전파 수행, optimizer 변수에 포함시킨 variable들의 gradient가 계산됨
    optimizer.step() # lr을 활용해서 variable들 업데이트

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Weight : {weight.item():.3f}, Bias : {bias.item():.3f}, Cost : {cost:.3f}")

Epoch : 1000, Weight : 0.864, Bias : -0.138, Cost : 1.393
Epoch : 2000, Weight : 0.870, Bias : -0.251, Cost : 1.380
Epoch : 3000, Weight : 0.873, Bias : -0.321, Cost : 1.375
Epoch : 4000, Weight : 0.875, Bias : -0.364, Cost : 1.373
Epoch : 5000, Weight : 0.877, Bias : -0.391, Cost : 1.373
Epoch : 6000, Weight : 0.878, Bias : -0.408, Cost : 1.372
Epoch : 7000, Weight : 0.878, Bias : -0.419, Cost : 1.372
Epoch : 8000, Weight : 0.878, Bias : -0.425, Cost : 1.372
Epoch : 9000, Weight : 0.879, Bias : -0.429, Cost : 1.372
Epoch : 10000, Weight : 0.879, Bias : -0.432, Cost : 1.372


### torch.nn.Linear
- layer = torch.nn.Linear(in_features, out_features)
- 입력 데이터에 y=Wx+b의 linear transformation을 적용함
- 입력은 in_features의 차원 크기, 출력은 out_features의 차원 크기를 가짐

In [ ]:
# 예제 3.26~3.28 신경망 패키지 적용

import torch
from torch import nn
from torch import optim

# 데이터 선언
x = torch.FloatTensor([
    [1], [2], [3], [4], [5], [6], [7], [8], [9], [10],
    [11], [12], [13], [14], [15], [16], [17], [18], [19], [20],
    [21], [22], [23], [24], [25], [26], [27], [28], [29], [30]
])
y = torch.FloatTensor([
    [0.94], [1.98], [2.88], [3.92], [3.96], [4.55], [5.64], [6.3], [7.44], [9.1],
    [8.46], [9.5], [10.67], [11.16], [14], [11.83], [14.4], [14.25], [16.2], [16.32],
    [17.46], [19.8], [18], [21.34], [22], [22.5], [24.57], [26.04], [21.6], [28.8]
])

# 모델 선언
model = nn.Linear(1, 1)

# 손실 함수, optimizer 선언
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

# epoch  설정
for epoch in range(10000):

    # 순방향
    output = model(x)
    cost = criterion(output, y)

    # 역방향
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.8761]], requires_grad=True), Parameter containing:
tensor([-0.3800], requires_grad=True)], Cost : 1.373
Epoch : 2000, Model : [Parameter containing:
tensor([[0.8772]], requires_grad=True), Parameter containing:
tensor([-0.4011], requires_grad=True)], Cost : 1.372
Epoch : 3000, Model : [Parameter containing:
tensor([[0.8778]], requires_grad=True), Parameter containing:
tensor([-0.4143], requires_grad=True)], Cost : 1.372
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8782]], requires_grad=True), Parameter containing:
tensor([-0.4225], requires_grad=True)], Cost : 1.372
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8785]], requires_grad=True), Parameter containing:
tensor([-0.4275], requires_grad=True)], Cost : 1.372
Epoch : 6000, Model : [Parameter containing:
tensor([[0.8786]], requires_grad=True), Parameter containing:
tensor([-0.4307], requires_grad=True)], Cost : 1.372
Epoch : 7000, Model : [Parameter contain

In [ ]:
# 예제 3.29~3.33 Dataset를 사용한 다중 선형 회귀

import torch
from torch import nn
from torch import optim
from torch.utils.data import TensorDataset, DataLoader

# 데이터 선언
train_x = torch.FloatTensor([
    [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [6, 7]
])
train_y = torch.FloatTensor([
    [0.1, 1.5], [1, 2.8], [1.9, 4.1], [2.8, 5.4], [3.7, 6.7], [4.6, 8]
])

# Dataset 선언
train_dataset = TensorDataset(train_x, train_y)
train_dataloader = DataLoader(train_dataset, batch_size=2, shuffle=True, drop_last=True)

# 모델, 손실 함수, optimizer 선언
model = nn.Linear(2, 2, bias=True)
criterion = nn.MSELoss()
optimizer = optim.SGD(model.parameters(), lr=0.001)

# epoch 설정
for epoch in range(20): # 20000
    cost = 0.0

    # batch 단위로 학습 진행
    for batch in train_dataloader:
        x, y = batch
        output = model(x)

        loss = criterion(output, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        cost += loss

    cost = cost / len(train_dataloader) # batch 평균 손실값 계산

    if (epoch + 1) % 1000 == 0:
        print(f"Epoch : {epoch+1:4d}, Model : {list(model.parameters())}, Cost : {cost:.3f}")

Epoch : 1000, Model : [Parameter containing:
tensor([[0.5092, 0.2116],
        [0.7116, 0.5305]], requires_grad=True), Parameter containing:
tensor([-0.2558, -0.0863], requires_grad=True)], Cost : 0.061
Epoch : 2000, Model : [Parameter containing:
tensor([[0.6914, 0.1173],
        [0.7705, 0.5000]], requires_grad=True), Parameter containing:
tensor([-0.5323, -0.1756], requires_grad=True)], Cost : 0.016
Epoch : 3000, Model : [Parameter containing:
tensor([[0.7841, 0.0692],
        [0.8005, 0.4845]], requires_grad=True), Parameter containing:
tensor([-0.6731, -0.2211], requires_grad=True)], Cost : 0.004
Epoch : 4000, Model : [Parameter containing:
tensor([[0.8315, 0.0448],
        [0.8158, 0.4766]], requires_grad=True), Parameter containing:
tensor([-0.7449, -0.2443], requires_grad=True)], Cost : 0.001
Epoch : 5000, Model : [Parameter containing:
tensor([[0.8556, 0.0324],
        [0.8235, 0.4726]], requires_grad=True), Parameter containing:
tensor([-0.7814, -0.2561], requires_grad=True)]